---

- name: Copy rabbitmq exporter script
  ansible.builtin.template:
    src: "rabbitmq_exporter"
    dest: /usr/local/bin/rabbitmq_exporter
    mode: 0755
    owner: root
    group: root

- name: Copy rabbitmq exporter script
  ansible.builtin.template:
    src: "rabbitmq_exporter.service"
    dest: /etc/systemd/system/rabbitmq_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Restart rabbitmq exporter service is restarted
  ansible.builtin.service:
    name: Rabbitmq_exporter
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for rabbitmq exporter to become ready
  ansible.builtin.wait_for:
    host: "{{ rabbitmq_exporter_server_bind }}"
    port: "{{ rabbitmq_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
