---

- name: copy rabbitmq exporter script
  template:
    src: "rabbitmq_exporter"
    dest: /usr/local/bin/rabbitmq_exporter
    mode: 0755
    owner: root
    group: root

- name: copy rabbitmq exporter script
  template:
    src: "rabbitmq_exporter.service"
    dest: /etc/systemd/system/rabbitmq_exporter.service
    mode: 0644
    owner: root
    group: root

- name: restart rabbitmq exporter service is restarted
  service:
    name: rabbitmq_exporter
    state: restarted
  changed_when: false

- name: wait for rabbitmq exporter to become ready
  wait_for:
    host: "{{ rabbitmq_exporter_server_bind }}"
    port: "{{ rabbitmq_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300