---
# handlers for ansible-role-docker-rabbitmq_exporter

- name: restart rabbitmq_exporter
  service:
    name: rabbitmq_exporter
    state: restarted
    enabled: true

- name: start rabbitmq_exporter
  service:
    name: rabbitmq_exporter
    state: started
    enabled: true

- name: reload rabbitmq_exporter
  service:
    name: rabbitmq_exporter
    state: reloaded
    enabled: true
